= Quick Start Guide - Restcomm Cloud


Restcomm Cloud is a commercial Cloud-hosted offering of the Restcomm Open Source platform. No more need to manually deploy and configure everything on your own. Instead you can https://www.restcomm.com/sign-up[sign up for a Cloud account] and try out some of the Restcomm features.

The web-based Admin console, allows you to manage your account resources:

	* Numbers
	* Applications
	* SIP Clients
	* Logs / Reports


== 1. Numbers

Search for and purchase phone numbers to later bind to specific applications.

While searching for phone numbers, keep in mind that some only allow receiving incoming calls. Others, known as “SMS enabled phone numbers”, support SMS messaging. There are also short code phone numbers, that you can use at your convenience to easily test different functionalities.

The following list of short code phone numbers is bind to Restcomm demo application and aims to help you test couple of the platform’s main functionalities.


	* 1235 - bound to a Hello World! demo application which greets you in different languages; You must have configured a text-to-speech engine (such as VoiceRSS, Acapella or another TTS) in order to use this application. 
	* 1236 - bound to a Gather verb demo application which prompts you to enter a digit and then plays it back for you. You need a TTS service configured to have the application fully functional.
	* 1234 - bound to Play verb demo application that plays back a pre-recorded media file.

== 2. Applications
To make an application functional, same needs to be bound to a registered phone number. 
There are three types of Restcomm applications: Voice, SMS and USSD. Triggering an application depends on its type.

	* A Voice application is triggered when a call is made to the corresponding phone number
	* An SMS application is triggered when SMS is sent to the corresponding phone number.
	* A USSD application is triggered when a short code is sent to the corresponding phone number.
	
Once started, the application fires up a serie of business logic events, that define how the interaction will continue. Based on the application type, these events may include:

	* Interactive Voice Response (IVR) menus (Playing audio, text-to-speech, collecting caller’s dial pad input, dialing phone numbers/joining a conference room, recording audio, etc.)
	* Sending SMS messages
	* Sending an email
	* Sending a fax
	* Calling an external web service (while integrating with 3rd party services)
	* And much more complex scenarios!

To let you combine and use all of these in your application, Restcomm Cloud utilizes a web-based Visual designer. Its intuitive interface allows you to drag and drop different elements and design your own flows.

Creating an application only takes couple of clicks.  Restcomm users may choose between three options:

	* To create an application from scratch using the Visual designer
	
	* To import a previously created one
	
	* Or to register an  externally hosted application



=== 2.1. Creating a Visual designer application from scratch 

To create a Visual designer application:

	* Navigate to Applications -> Add new app
	
	* Choose your application type

Next, you will be redirected to the Template Gallery where you can see example of applications you can build. To get started, choose the one that fits best your application use case.

	* **Empty** - lets you start with an empty canvas
	
	* **SMS Echo** - send an SMS to a phone number and receive it back as an auto-reply
	
	* **IVR Menu**:  - build an interactive menu you could encounter in a typical call center
	
	* **USSD Menu** - Have you ever dialed numbers like *101# from your mobile? That’s what USSD is. This template shows you how to use these USSD“Short codes” also known as “Feature codes” 
	
https://www.restcomm.com/docs/connect/rvd/index.html[Learn more] about how to use Visual designer itself to create your own application scenarios.



=== 2.2. Importing a Visual designer application
You can upload a RCML application under your Restcomm account into the Cloud. 



=== 2.3. Creating an externally hosted application
Define the external URL of a RCML application. Same needs to return as response the RCML body of the application in order to make it work.



== 3. SIP clients
SIP clients are actual SIP accounts which can be used on different devices and SIP phones to make and receive calls.



=== 3.1. Creating a SIP client from the Restcomm Console
To create a new SIP client, simply navigate to Dashboard -> Clients -> New client. You will be prompted to set a username and password for the new client.



=== 3.2. Connecting to a Restcomm SIP client from a SIP phone
Dial the following SIP address to connect from your SIP phone to your Restcomm client: <username>@cloud.restcomm.com.



=== 3.3. Defining a VoiceURL of a Restcomm SIP client
For each Restcomm SIP client, you can optionally define VoiceURL from the Console. That is an URL of a Voice application that will be invoked any time this SIP client attempts to dial any number.

To set a VoiceURL for your client navigate to your Dashboard -> Clients and select your SIP client from the list. From the Voice request drop down select Application and then choose the one you want to assign to your SIP client from the second drop down.



== 4. Logs
The Logs section of the Console Dashboards, provides detailed reports of the following event types:

	* Calls
	
	* SMS messages
	
	* Audio recordings
	
	* Transcriptions (using the Transcribe parameters of the Record verb)
	
	* Notifications

You can access all reports by navigating to Dashboard -> Logs.



== 5. Account settings
You can access your account settings by navigating to your username, at the top right corner of your screen. 



=== 5.1. Main Account settings
To access your main accounts settings, navigate to your username -> Account. You can change your password and get details about your Account SID and Auth Token.

The Auth Token is the password that is required in order to perform different  Restcomm-Connect API operations. You can reveal the hashed password by clicking on the button eye button next to it.



=== 5.2. Sub-account settings
Under your main Account settings you will find an option to create sub-accounts. In general, sub-accounts are used to separate the usage of specific phone numbers and the applications bound to them. 

For example, if you have registered two phone numbers, you can create two sub-accounts and have each one of them manage only one number. In this case no sub-account will have the right to manage a number that doesn’t belong to it.
Your man account can manage the permissions of both of the sub-accounts. 

For more information, please visit the https://www.restcomm.com/docs/connect/api/Restcomm%20-%20Multi-tenancy%20and%20Managing%20Sub-Accounts.html[sub-accounts-documentation].

